# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test2(self):
    self.driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
    self.driver.set_window_size(1054, 808)
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("Admin")
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-sheet > .oxd-text:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-sheet > .oxd-text:nth-child(2)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".oxd-sheet > .oxd-text:nth-child(2)")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("admin123")
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-chevron-left").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-chevron-right").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-userdropdown-name").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
  
