# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTest2:
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_test2(self):
        self.driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
        self.driver.set_window_size(1054, 808)
        time.sleep(3)
        self.driver.find_element(By.XPATH, "//input[@name=\'username\']").click()
        self.driver.find_element(By.XPATH, "//input[@name=\'username\']").send_keys("Admin")
        # username = self.driver.find_element(By.XPATH, "//div[2]/input")

        # self.driver.find_element(By.CSS_SELECTOR, ".oxd-sheet > .oxd-text:nth-child(2)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".oxd-sheet > .oxd-text:nth-child(2)").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".oxd-sheet > .oxd-text:nth-child(2)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.XPATH, "//input[@name=\'password\']").click()
        self.driver.find_element(By.XPATH, "//input[@name=\'password\']").send_keys("admin123")
        self.driver.find_element(By.CSS_SELECTOR, ".oxd-button").click()
        time.sleep(3)
        # self.driver.find_element(By.XPATH, "//div[@id=\'app\']/div/div/aside/nav/div[2]/div/div/button/i").click()
        # self.driver.find_element(By.XPATH, "//div[@id=\'app\']/div/div/aside/nav/div[2]/div/div/button/i").click()
        self.driver.find_element(By.CSS_SELECTOR, ".oxd-userdropdown-name").click()
        time.sleep(3)
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Logout')]").click()
        # self.driver.find_element(By.LINK_TEXT, "Logout").click()
